### ISSUE TITLE
How do you deal with agent dependency updates

### ISSUE THREAD

**Issue by neok-g** [antsok/ado-aca#13]
Hi,

First of all nice work! 

Question: how do you deal with agent dependency updates e.g. Azure CLI or Azure PowerShell?
Does this imply that the docker file needs to be modified or is the docker file more or less static?

Could you elloborate?

Thank you!

Koen

**Comment by antsok** [comment]
Azure CLI and Powershell binaries are updated to the latest version every time the agent image is built

See Dockerfile ...
`RUN curl -LsS https://aka.ms/InstallAzureCLIDeb | bash`
`RUN apt-get install -y --no-install-recommends powershell`
