### ISSUE TITLE
How do these scaling rules work?

### ISSUE THREAD

**Issue by neok-g** [antsok/ado-aca#14]
Hi,

How do these scaling rules work:

If one of these 2 rules fire then one instance is added?
So these rules would fire only once or?

          {
            name: 'cpu-scaling-rule'
            custom: {
              type: 'cpu'
              metadata: {
                type: 'Utilization'
                value: '25'
              }
            }
          }
          {
            name: 'memory-scaling-rule'
            custom: {
              type: 'memory'
              metadata: {
                type: 'Utilization'
                value: '50'
              }
            }
          }

**Comment by antsok** [comment]
The code mentioned will be removed in my future updates, as it makes no sense to scale based on agent utilization. But if you want to read about those rules please refer to this doc https://learn.microsoft.com/en-us/azure/container-apps/scale-app?pivots=azure-cli
